#+title: My philosophy on life
#+date: 2023-12-23

This may be a little depressing.

I'm basically an antinatalist. That means I think (human) life is a net negative, and human consciousness is an evolutionary dead-end.

Now, if you've seen the A-word around the internet, you've probably seen it in conjunction with a bunch of edgy angry doomers yelling about "breeders." That's not me. My reason is essentially the First Noble Truth, although I wouldn't call myself Buddhist.[fn::I've spoken to a lot of committed Buddhists and I see the utility of believing in reincarnation and karma, but haven't made a serious study myself.] To be human is to suffer, uniquely, because we wake up every morning knowing we're guaranteed to die. Human civilization and everything that comes with it is our attempt at trying to forget this, but we can't and won't.

Animals suffer too; that's why I'm a vegan. I can't stop them from eating each other, but I can at least stop the animals I won't eat from being born and tortured and killed.[fn::I think it's important to say that they're never killed only because they're never born. They don't, after all, let animals out of slaughterhouses, do they?]

Be compassionate to the people you see, and be compassionate to yourself. Every human is suffering from a cruel joke played on us by the cosmos. Every last one, no matter how little or how much they have. They -- we -- never had a chance. But we can still live our best lives while we're here.

And please don't have any more kids.

If you want references, try:
- Peter Wessel Zapffe, /The Last Messiah/
- Peter Watts, /Blindsight/
- Ernest Becker, /The Denial of Death/
- Jon Bois, /17776/
- the documentary /Dominion/, dir. Delforce

All are available freely online or at your local library. Be warned that these are emotionally draining reads/watches.
